posts/urls.py
from django.views.generic import RedirectView
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    LikeView
)
app_name = "posts"
urlpatterns = [
    path('', RedirectView.as_view(url="")),
    path('search/', PostListView.as_view(), name="list"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('<int:pk>/', PostDetailView.as_view(), name="detail"),
    path('like/<int:pk>/', LikeView, name="like_post"),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name="edit"),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),
]

tags/urls.py
from django.urls import path
from .views import (
    TagListView,
    TagDetailView
)
app_name = "tags"
urlpatterns = [
    path('', TagListView.as_view(), name="list"),
    path('<slug:slug>/', TagDetailView.as_view(), name="detail"),
]

travel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import UserRegisterView
from posts.views import PostListView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', PostListView.as_view(), name='home'),
    path('post/', include('posts.urls', namespace='posts')),
    path('tag/', include('tags.urls', namespace='tags')),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls')),
    path('', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def add_count(self, user, post):
        obj, created = self.model.objects.get_or_create(
            user=user,
            post=post
        )
        obj.count = obj.count_likes.count()
        obj.save()
        return obj


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=2000)
    image = models.ImageField(default='default.jpg', upload_to='post_image/')
    update = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='blog_posts')

    def __str__(self):
        return f"{self.id}"

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"pk": self.pk})

    class Meta:
        ordering = [
            '-timestamp'
        ]

tags/models.py
from django.db import models

# Create your models here.
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.text import slugify

from posts.models import Post


class TagQuerySet(models.QuerySet):
    def active(self):
        return self.filter(active=True)


class TagManager(models.Manager):
    def get_queryset(self):
        return TagQuerySet(self.model, using=self._db)

    def all(self, *args, **kwargs):
        return super(TagManager, self).all(*args, **kwargs).filter(active=True)


class Tag(models.Model):
    title = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(unique=True)
    posts = models.ManyToManyField(Post, blank=True)
    active = models.BooleanField(default=True)

    objects = TagManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("tags:detail", kwargs={"slug": self.slug})


def tag_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)


pre_save.connect(tag_pre_save_receiver, sender=Tag)

posts/forms.py
from django import forms

from .models import Post


class PostModelForm(forms.ModelForm):
    tags = forms.CharField(label='tag', required=False)

    class Meta:
        model = Post
        fields = ["title", "image"]

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if len(title) <= 3:
            raise forms.ValidationError(
                "Length has to be more than 3 character"
            )
        return title

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView
)
from analytics.models import TagView
from tags.models import Tag
from .forms import PostModelForm
from .mixins import FormUserMixin, UserOwnerMixin
from .models import Post


class PostCreateView(FormUserMixin, CreateView):
    form_class = PostModelForm
    template_name = "posts/post_create.html"

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        valid_data = super(PostCreateView, self).form_valid(form)
        tags = form.cleaned_data.get("tags")
        if tags:
            tags_list = tags.split(',')
            for tag in tags_list:
                if not tag == " ":
                    new_tag = Tag.objects.get_or_create(
                        title=str(tag).strip())[0]
                    new_tag.posts.add(form.instance)
        return valid_data


class PostUpdateView(LoginRequiredMixin, UserOwnerMixin, UpdateView):
    queryset = Post.objects.all()
    form_class = PostModelForm
    template_name = "posts/post_update.html"

    def get_initial(self):
        initial = super(PostUpdateView, self).get_initial()
        tags = self.get_object().tag_set.all()
        initial['tags'] = ", ".join([x.title for x in tags])
        return initial

    def form_valid(self, form):
        valid_data = super(PostUpdateView, self).form_valid(form)
        tags = form.cleaned_data.get("tags")
        obj = self.get_object()
        obj.tag_set.clear()
        if tags:
            tags_list = tags.split(',')
            for tag in tags_list:
                if not tag == " ":
                    new_tag = \
                    Tag.objects.get_or_create(title=str(tag).strip())[0]
                    new_tag.posts.add(self.get_object())
        return valid_data


class PostDetailView(DetailView):
    queryset = Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        stuff = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = stuff.total_likes()

        liked = False
        if stuff.likes.filter(id=self.request.user.id).exists():
            liked = True
        context['total_likes'] = total_likes
        context['liked'] = liked
        obj = self.get_object()
        tags = obj.tag_set.all()
        for tag in tags:
            new_view_tag = TagView.objects.add_count(
                self.request.user, tag
            )
        return context


def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False

    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('posts:detail', args=[str(pk)]))


class PostListView(LoginRequiredMixin, ListView):
    paginate_by = 8
    model = Post

    def get_queryset(self, *args, **kwargs):
        qs = Post.objects.all()
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query) |
                Q(user__username__icontains=query)
            )
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_form'] = PostModelForm
        context["create_url"] = reverse_lazy("posts:create")
        return context


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = "posts/post_delete.html"
    success_url = reverse_lazy("posts:list")

templates/posts/forms.html
{% load crispy_forms_tags %}

<form id = '{% if form_id %}{{ form_id }}{% endif %}' class="form-group "
      method="POST" action="{% if action_url %}{{ action_url }}{% endif %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-outline-success mt-2" type="submit" value="{{ btn_value }}">
</form>

templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}{{ block.super }}Create{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
        <div class="col-sm-6 ">
            {% include "posts/forms.html" with form=form btn_value='Post' %}
        </div>
        </div>
    </div>
{% endblock %}

templates/posts/post_delete.html
{% extends "base.html" %}
{% block title %}{{  block.super  }}Delete{% endblock %}
{% block content %}
    <div class="container">
	<div class="row">
        <div class="col-md-8 col-md-offset-2 col-xs-12">
            <div class="mainheading">
                <form action="" method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">
                            Delete Post
                        </legend>
                        <h2>Sure u wanna delete {{ post.title }}?</h2>
                    </fieldset>
                    <div class="form-group mt-3">
                        <button class="btn btn-outline-danger" type="submit">
                            Delete
                        </button>
                        <a class="btn btn-outline-secondary" href="{% url 'posts:detail' post.id %}">
                            Cancel
                        </a>
                    </div>
{#                    <input type="submit" value="Confirm">#}
                </form>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/posts/post_detail.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load static %}
{% load rec_posts %}

{% block title %}{{ block.super }}{{ post.title }}{% endblock %}
{% block content %}
    <div class="container">
	<div class="row">
        <div class="col-md-2 col-xs-12">
			<div class="share">
            <div class="sep">
            </div>
            <ul>
             {% if object.user == user %}
{#                <div class="mt-2">#}
                    <li><a class="btn-outline-secondary btn-sm mt-1 mb-1" href="{% url 'posts:edit' post.id %}">Update</a></li>
                    <li><a class="btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'posts:delete' post.id %}">Delete</a></li>
{#                </div>#}
                 <div class="sep">
                </div>
            {% endif %}

                <li>
                    <form action="{% url 'posts:like_post' post.pk %}"
                      method='POST'>
                    {% csrf_token %}
                    {% if user.is_authenticated %}
                        {% if liked %}
                            <button type="submit"
                                    name="post_id"
                                    value="{{ post.id }}"
                                    class="btn btn-primary btn-sm">
                                Unlike
                            </button>
                        {% else %}
                            <button type="submit"
                                    name="post_id"
                                    value="{{ post.id }}"
                                    class="btn btn-primary btn-sm">
                                Like
                            </button>
                        {% endif %}
                    {% else %}
                        <small>Login to like</small>
                    {% endif %}
                    - {{ total_likes }} like{% if total_likes > 1 %}s
                {% else %}{% endif %}

                </form>

                </li>

            </ul>

{#				<div class="sep">#}
{#				</div>#}
{#				<ul>#}
{#					<li>#}
{#					<a href="#comments">#}
{#					42<br/>#}
{#					<svg class="svgIcon-use ml-2" width="32" height="32" viewbox="0 0 29 29"><path d="M9.719,17.073l-6.562-6.51c-0.27-0.268-0.504-0.567-0.696-0.888C1.385,7.89,1.67,5.613,3.155,4.14c0.864-0.856,2.012-1.329,3.233-1.329c1.924,0,3.115,1.12,3.612,1.752c0.499-0.634,1.689-1.752,3.612-1.752c1.221,0,2.369,0.472,3.233,1.329c1.484,1.473,1.771,3.75,0.693,5.537c-0.19,0.32-0.425,0.618-0.695,0.887l-6.562,6.51C10.125,17.229,9.875,17.229,9.719,17.073 M6.388,3.61C5.379,3.61,4.431,4,3.717,4.707C2.495,5.92,2.259,7.794,3.145,9.265c0.158,0.265,0.351,0.51,0.574,0.731L10,16.228l6.281-6.232c0.224-0.221,0.416-0.466,0.573-0.729c0.887-1.472,0.651-3.346-0.571-4.56C15.57,4,14.621,3.61,13.612,3.61c-1.43,0-2.639,0.786-3.268,1.863c-0.154,0.264-0.536,0.264-0.69,0C9.029,4.397,7.82,3.61,6.388,3.61"></path></svg>#}
{#					</a>#}
{#					</li>#}
{#				</ul>#}
			</div>
		</div>
		<!-- End Fixed Left Share -->
        <div class="col-md-8 col-md-offset-2 col-xs-12">
			<div class="mainheading">

				<!-- Begin Top Meta -->
				<div class="row post-top-meta">
					<div class="col-md-2">
						<a href="{% url "accounts:detail" post.user %}"><img class="author-thumb" src="https://www.gravatar.com/avatar/e56154546cf4be74e393c62d1ae9f9d4?s=250&amp;d=mm&amp;r=x" alt="Sal"></a>
					</div>
					<div class="col-md-10">
						<a class="link-dark" href="{% url "accounts:detail" post.user %}">{{ post.user.username }}</a>

					</div>
				</div>
				<!-- End Top Menta -->

				<h1 class="posttitle">{{ post.title }}</h1>
                <span class="post-date">{{ post.timestamp }}</span>

			</div>

			<!-- Begin Featured Image -->
			<img class="featured-image img-fluid" src="https://source.unsplash.com/random/" alt="">
			<!-- End Featured Image -->

			<!-- Begin Post Content -->
			<div class="article-post">
				<p>
					Holy grail funding non-disclosure agreement advisor ramen bootstrapping ecosystem. Beta crowdfunding iteration assets business plan paradigm shift stealth mass market seed money rockstar niche market marketing buzz market.
				</p>
				<p>
					Burn rate release facebook termsheet equity technology. Interaction design rockstar network effects handshake creative startup direct mailing. Technology influencer direct mailing deployment return on investment seed round.
				</p>
				<p>
					 Termsheet business model canvas user experience churn rate low hanging fruit backing iteration buyer seed money. Virality release launch party channels validation learning curve paradigm shift hypotheses conversion. Stealth leverage freemium venture startup business-to-business accelerator market.
				</p>
				<blockquote>
					Gen-z strategy long tail churn rate seed money channels user experience incubator startup partner network low hanging fruit direct mailing. Client backing success startup assets responsive web design burn rate A/B testing metrics first mover advantage conversion.
				</blockquote>
				<p>
					Freemium non-disclosure agreement lean startup bootstrapping holy grail ramen MVP iteration accelerator. Strategy market ramen leverage paradigm shift seed round entrepreneur crowdfunding social proof angel investor partner network virality.
				</p>
			</div>
			<!-- End Post Content -->

			<!-- Begin Tags -->

			<div class="after-post-tags">
				<ul class="tags">
					<li>{% for tag in post.tag_set.all %}
                        <a href="{% url "tags:detail" tag.slug %}"
                        >{{ tag.title }}</a>
                    {% empty %}
                    {% endfor %}</li>
				</ul>
			</div>
			<!-- End Tags -->

		</div>
		<!-- End Post -->

    </div>
    <div class="hideshare"></div>

    </div>
    <div class="graybg">
	<div class="container">
        <div class="row listrecent listrelated">
            <!-- begin post -->
            {% rec_posts request.user %}
		<!-- end post -->
        </div>
    </div>
    </div>
{% endblock %}

templates/posts/post_list.html
{% extends "base.html" %}
{% load static %}
{% load recommended %}
{% load rec_tags %}
{% load rec_posts %}
{% block title %}{{ block.super }}Posts{% endblock %}
{% block script %}
{% endblock %}
{% block content %}
    <!-- Begin Site Title
    ================================================== -->
    <div class="container">
        <div class="mainheading">
            <h1 class="sitetitle">All Post</h1>
        </div>
        <!-- End Site Title
        ================================================== -->
        <!-- Begin Tags -->
        {% rec_tags request.user %}
        <!-- End Tags -->
        <!-- Begin Featured
        ================================================== -->
        <section class="featured-posts">
            <div class="section-title">
                <h2><span>Recent</span></h2>
            </div>
            <div class="card-columns listfeaturedtag">

                <!-- begin post -->
                {% for object in object_list %}
                    <div class="card">
                        <div class="row">
                            <div class="col-md-5 wrapthumbnail">
                                <a href="{{ object.get_absolute_url }}">
                                    <div class="thumbnail"
                                         style="background-image:url({{ object.image.url }});">
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-7">
                                <div class="card-block">
                                    <h2 class="card-title"><a
                                            href="{{ object.get_absolute_url }}">{{ object.title }}</a>
                                    </h2>
                                    <h4 class="card-text">This is a longer card
                                        with supporting text below as a natural
                                        lead-in to additional content. This
                                        content is a little bit longer.</h4>
                                    <div class="metafooter">
                                        <div class="wrapfooter">
                                <span class="meta-footer-thumb">
                                <a href="author.html"><img class="author-thumb"
                                                           src="https://www.gravatar.com/avatar/e56154546cf4be74e393c62d1ae9f9d4?s=250&amp;d=mm&amp;r=x"
                                                           alt="Sal"></a>
                                </span>
                                            <span class="author-meta">
                                <span class="post-name"><a
                                        href="{% url "accounts:detail" object.user.username %}">{{ object.user.username }}</a></span><br/>
                                <span class="post-date">{{ object.timestamp|timesince }}</span><span
                                                    class="dot"></span><span
                                                    class="post-read">
                                <span class="post-read-more"><a
                                        href="{{ object.get_absolute_url }}"
                                        title="Read Story"><svg
                                        class="svgIcon-use" width="25"
                                        height="25" viewbox="0 0 25 25"><path
                                        d="M19 6c0-1.1-.9-2-2-2H8c-1.1 0-2 .9-2 2v14.66h.012c.01.103.045.204.12.285a.5.5 0 0 0 .706.03L12.5 16.85l5.662 4.126a.508.508 0 0 0 .708-.03.5.5 0 0 0 .118-.285H19V6zm-6.838 9.97L7 19.636V6c0-.55.45-1 1-1h9c.55 0 1 .45 1 1v13.637l-5.162-3.668a.49.49 0 0 0-.676 0z"
                                        fill-rule="evenodd"></path></svg></a></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end post -->
                {% empty %}
                    {% if request.GET.q %}
                        <p>No Post found.</p>
                    {% else %}
                        <p>No Posts yet.</p>
                    {% endif %}
                {% endfor %}
            </div>
        </section>
        <!-- End Featured
        ================================================== -->

        <section class="recent-posts">
            <div class="section-title">
                <h2><span>Recommended Posts</span></h2>
            </div>
            <div class="graybg">
                <div class="container">
                    <div class="row listrecent listrelated">
                        <!-- begin post -->
                        {% rec_posts request.user %}
                        <!-- end post -->
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            {% if page_obj.number != None %}
                Page {{ page_obj.number }} of
                {{ page_obj.paginator.num_pages }}.
            {% else %}
            {% endif %}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>




{% endblock %}

templates/posts/post_update.html
{% extends "base.html" %}
{% block title %}{{ block.super }}Edit{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 ">
                {% include "posts/forms.html" with form=form btn_value='Edit' %}
            </div>


        </div>
    </div>

{% endblock %}

templates/posts/search_form.html
{#<form id="navbar-search-form" class="d-flex" method="GET" action="{% url 'posts:list' %}">#}
{#    <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">#}
{#    <button class="btn btn-outline-success" type="submit">Search</button>#}
{#</form>#}
<!-- Begin Search -->
<form id="navbar-search-form" class="form-inline my-2 my-lg-0" method="GET" action="{% url 'posts:list' %}">
    <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" value="{{ request.GET.q }}">
    <span class="search-icon"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M20.067 18.933l-4.157-4.157a6 6 0 1 0-.884.884l4.157 4.157a.624.624 0 1 0 .884-.884zM6.5 11c0-2.62 2.13-4.75 4.75-4.75S16 8.38 16 11s-2.13 4.75-4.75 4.75S6.5 13.62 6.5 11z"></path></svg></span>
</form>
<!-- End Search -->