posts/urls.py
from django.views.generic import RedirectView
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    LikeView
)
app_name = "posts"
urlpatterns = [
    path('', RedirectView.as_view(url="")),
    path('search/', PostListView.as_view(), name="list"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('<int:pk>/', PostDetailView.as_view(), name="detail"),
    path('like/<int:pk>/', LikeView, name="like_post"),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name="edit"),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),
]

tags/urls.py
from django.urls import path
from .views import (
    TagListView,
    TagDetailView
)
app_name = "tags"
urlpatterns = [
    path('', TagListView.as_view(), name="list"),
    path('<slug:slug>/', TagDetailView.as_view(), name="detail"),
]

travel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import UserRegisterView
from posts.views import PostListView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', PostListView.as_view(), name='home'),
    path('post/', include('posts.urls', namespace='posts')),
    path('tag/', include('tags.urls', namespace='tags')),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls')),
    path('', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta charset="utf-8">
<!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
<!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/mediumish.css' %}">
    <title>{% block title %}Travel | {% endblock %}</title>

</head>
<body>
    {% include "navbar.html" %}

    {% block content %}

    {% endblock %}
{% block script %}{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}{{  block.super  }}Home page{% endblock %}
{% block content %}
<h1>mad</h1>
{% endblock %}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">
<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="container">
	<!-- Begin Logo -->
	<a class="navbar-brand" href="{% url 'home' %}">
	<img src="{% static 'img/logo.png' %}" alt="logo">
	</a>
	<!-- End Logo -->
	<div class="collapse navbar-collapse" id="navbarsExampleDefault">
		<!-- Begin Menu -->

		<ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:list' %}">Posts</a>
			</li>
			<li class="nav-item">
			    <a class="nav-link" href="{% url 'posts:create' %}">Create Posts</a>
			</li>
			<li class="nav-item">
			    <a class="nav-link" href="{% url 'logout' %}">Log out</a>
			</li>
            <li class="nav-item">
			    <a class="nav-link" href="{% url 'accounts:detail' request.user.username %}">Profile</a>
			</li>
            {% else %}
            <li class="nav-item">
			    <a class="nav-link" href="{% url 'register' %}">Register</a>
			</li>
			<li class="nav-item">
			    <a class="nav-link" href="{% url 'login' %}">Log In</a>
			</li>
            {% endif %}
		</ul>
		<!-- End Menu -->
		<!-- Begin Search -->
        {% include "posts/search_form.html" %}
		<!-- End Search -->
	</div>
</div>
</nav>
<!-- End Nav
================================================== -->